name: Docker image

on:
  release:
    types: [published]

jobs:
  publish-web:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling repo
        uses: actions/checkout@v1
      - name: Building image
        run: docker build . -t docker.pkg.github.com/$GITHUB_REPOSITORY/web:$GITHUB_SHA -t docker.pkg.github.com/$GITHUB_REPOSITORY/web:latest
      - name: Loging in
        run: docker login docker.pkg.github.com -u $(cut -d/ -f1 <<< $GITHUB_REPOSITORY) -p ${{ secrets.GITHUB_TOKEN }}
      - name: Pushing image
        run: |
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/web:$GITHUB_SHA
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/web:latest
